<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="DomainTests.fs" />
		<Compile Include="SubtitleTests.fs" />
		<Compile Include="IntegrationTests.fs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="FsUnit.xUnit" Version="7.1.1" />
		<ProjectReference Include="..\Core\DirectoryCleaner.fsproj" />
		<PackageReference Update="FSharp.Core" Version="10.0.100" />
	</ItemGroup>

</Project>